version: '3.8'

services:
  # Build and test service
  jaxws-builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: |
      bash -c "
        echo 'Running comprehensive tests for all JAX-WS projects'
        
        # Test each Maven project
        for project in double.it doubleIt ws.security.sample wssecurity.map; do
          if [ -d \$$project ]; then
            echo '=== Testing project: '\$$project' ==='
            cd \$$project
            mvn clean test -B -Dmaven.test.failure.ignore=true
            cd ..
          fi
        done
        
        echo 'All tests completed'
      "

  # Runtime service testing with Tomcat
  jaxws-runtime:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx512m
    volumes:
      - ./x509:/opt/x509:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service testing with curl
  jaxws-tester:
    image: curlimages/curl:latest
    depends_on:
      jaxws-runtime:
        condition: service_healthy
    command: |
      sh -c "
        echo 'Testing deployed web services...'
        
        # Test Tomcat is running
        curl -f http://jaxws-runtime:8080/ || echo 'Tomcat base test completed'
        
        # Test deployed WAR files
        curl -f http://jaxws-runtime:8080/doubleit/ || echo 'Double.it service test completed'
        
        # Test WSDL endpoints if available
        curl -f http://jaxws-runtime:8080/doubleit/services?wsdl || echo 'WSDL endpoint test completed'
        
        echo 'Service testing completed'
      "

  # Security testing service
  security-tester:
    image: openjdk:8-jdk-alpine
    depends_on:
      - jaxws-runtime
    volumes:
      - ./x509:/opt/x509:ro
      - .:/workspace:ro
    working_dir: /workspace
    command: |
      sh -c "
        echo 'Running WS-Security tests...'
        
        # Check certificate files are available
        ls -la /opt/x509/ || echo 'X.509 certificates not found'
        
        # Test keystore access (basic validation)
        if [ -f '/opt/x509/client_sign_keystore.jks' ]; then
          echo 'Client keystore found'
        fi
        
        if [ -f '/opt/x509/server_keystore.jks' ]; then
          echo 'Server keystore found'  
        fi
        
        echo 'Security validation completed'
      "

# Networks for service communication
networks:
  default:
    driver: bridge

# Volumes for persistent data
volumes:
  maven-cache:
    driver: local