
package de.opitzconsulting.demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 13 12:33:05 CEST 2009
 * Generated source version: 2.2.3
 */

@XmlRootElement(name = "calcFinalPriceResponse", namespace = "http://demo.opitzconsulting.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calcFinalPriceResponse", namespace = "http://demo.opitzconsulting.de/")

public class CalcFinalPriceResponse {

    @XmlElement(name = "return")
    private double _return;

    public double getReturn() {
        return this._return;
    }

    public void setReturn(double new_return)  {
        this._return = new_return;
    }

}

