
package de.opitzconsulting.demo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 13 12:33:05 CEST 2009
 * Generated source version: 2.2.3
 */

@XmlRootElement(name = "calcFinalPrice", namespace = "http://demo.opitzconsulting.de/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calcFinalPrice", namespace = "http://demo.opitzconsulting.de/", propOrder = {"custId","basePrice"})

public class CalcFinalPrice {

    @XmlElement(name = "custId")
    private java.lang.String custId;
    @XmlElement(name = "basePrice")
    private double basePrice;

    public java.lang.String getCustId() {
        return this.custId;
    }

    public void setCustId(java.lang.String newCustId)  {
        this.custId = newCustId;
    }

    public double getBasePrice() {
        return this.basePrice;
    }

    public void setBasePrice(double newBasePrice)  {
        this.basePrice = newBasePrice;
    }

}

