
package de.opitzconsulting.demo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.3
 * Thu Aug 13 12:33:08 CEST 2009
 * Generated source version: 2.2.3
 * 
 */
 
public class CustDiscountCalculationServer{

    protected CustDiscountCalculationServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new de.opitzconsulting.demo.DiscountCalculator();
        String address = "http://localhost:9090/DiscountCalculatorPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new CustDiscountCalculationServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 